image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  
before_script:
  - dotnet tool install -g coverlet.console

build_and_StyleCope:
  stage: build
  script:
    - find . -name '*.csproj' ! -name '*Tests*' -exec dotnet build {} \;

test_and_Coverage:
  stage: test
  script:
    - find . -name '*Tests*.csproj' -exec dotnet test {} 
      --collect:"XPlat Code Coverage"
      --results-directory cobertura \;
    - cd cobertura
    - ls -l
  artifacts:
    paths:
       - cobertura/**/*.cobertura.xml


