image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test
  
before_script:
  - dotnet tool install -g coverlet.console

build_and_StyleCope:
  stage: build
  script:
    - find . -name '*.csproj' ! -name '*Tests*' -exec dotnet build {} \;

test:
  stage: test
  script:
    - find . -name '*Tests*.csproj' -exec dotnet test {} \;

coverage:
  stage: test
  script:
    - find . -name '*Tests*.csproj' -exec bash -c 'dotnet test "$1" && coverlet "$(dirname "$1")/bin/Debug/netcoreapp3.1/$(basename "$1" .csproj).dll" --target "dotnet" --targetargs "test $1 --no-build" --format opencover' _ {} \;
  artifacts:
    paths:
      - '**/*.coverage'
  dependencies:
    - test



